PrimeFaces.locales['sr'] = {
	closeText : 'Затвори',
	prevText : 'Назад',
	nextText : 'Напред',
	monthNames : [ 'Јануар', 'Фебруар', 'Март', 'Април', 'Мај', 'Јун', 'Јул',
			'Август', 'Септембар', 'Октобар', 'Новембар', 'Децембар' ],
	monthNamesShort : [ 'Јан', 'Феб', 'Мар', 'Апр', 'Мај', 'Јун', 'Јул', 'Авг',
			'Сеп', 'Окт', 'Нов', 'Дец' ],
	dayNames : [ 'Недеља', 'Понедељак', 'Уторак', 'Среда', 'Четвртак',
			'Петак', 'Субота' ],
	dayNamesShort : [ 'Нед', 'Пон', 'Уто', 'Сре', 'Чет', 'Петак', 'Суб' ],
	dayNamesMin : [ 'Н', 'П', 'У', 'С', 'Ч', 'П ', 'С' ],
	weekHeader : 'Недеља',
	firstDay : 1,
	isRTL : false,
	showMonthAfterYear : false,
	yearSuffix : '',
	timeOnlyTitle : 'Само Време',
	timeText : 'Време',
	hourText : 'Сат',
	minuteText : 'Минут',
	secondText : 'Секунд',
	currentText : 'Данас',
	ampm : false,
	month : 'Месец',
	week : 'недеља',
	day : 'Дан',
	allDayText : 'Цео дан'
};