//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 09:15:18 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Deo1Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Deo1Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PodaciOPodnosiocuPrijave" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OsnovneInformacije" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ImePrezime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Drzavljanstvo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DatumRodjenja" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="MestoRodjenja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Zanimanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Adresa" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AdresaStanovanja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Grad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="PostanskiBroj" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="Drzava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Pasos" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Broj" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="DatumIzdavanja" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="MestoIzdavanja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PodaciOVlasnikuSredstava" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OsnovneInformacije" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ImePrezime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Drzavljanstvo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DatumRodjenja" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="MestoRodjenja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Zanimanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Adresa" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AdresaStanovanja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Grad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="PostanskiBroj" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="Drzava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Pasos" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Broj" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="DatumIzdavanja" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="MestoIzdavanja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Deo1Type", propOrder = {
    "podaciOPodnosiocuPrijave",
    "podaciOVlasnikuSredstava"
})
public class Deo1Type {

    @XmlElement(name = "PodaciOPodnosiocuPrijave")
    protected Deo1Type.PodaciOPodnosiocuPrijave podaciOPodnosiocuPrijave;
    @XmlElement(name = "PodaciOVlasnikuSredstava")
    protected Deo1Type.PodaciOVlasnikuSredstava podaciOVlasnikuSredstava;

    /**
     * Gets the value of the podaciOPodnosiocuPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link Deo1Type.PodaciOPodnosiocuPrijave }
     *     
     */
    public Deo1Type.PodaciOPodnosiocuPrijave getPodaciOPodnosiocuPrijave() {
        return podaciOPodnosiocuPrijave;
    }

    /**
     * Sets the value of the podaciOPodnosiocuPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link Deo1Type.PodaciOPodnosiocuPrijave }
     *     
     */
    public void setPodaciOPodnosiocuPrijave(Deo1Type.PodaciOPodnosiocuPrijave value) {
        this.podaciOPodnosiocuPrijave = value;
    }

    /**
     * Gets the value of the podaciOVlasnikuSredstava property.
     * 
     * @return
     *     possible object is
     *     {@link Deo1Type.PodaciOVlasnikuSredstava }
     *     
     */
    public Deo1Type.PodaciOVlasnikuSredstava getPodaciOVlasnikuSredstava() {
        return podaciOVlasnikuSredstava;
    }

    /**
     * Sets the value of the podaciOVlasnikuSredstava property.
     * 
     * @param value
     *     allowed object is
     *     {@link Deo1Type.PodaciOVlasnikuSredstava }
     *     
     */
    public void setPodaciOVlasnikuSredstava(Deo1Type.PodaciOVlasnikuSredstava value) {
        this.podaciOVlasnikuSredstava = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OsnovneInformacije" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ImePrezime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Drzavljanstvo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DatumRodjenja" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="MestoRodjenja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Zanimanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Adresa" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AdresaStanovanja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Grad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="PostanskiBroj" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="Drzava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Pasos" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Broj" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="DatumIzdavanja" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="MestoIzdavanja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "osnovneInformacije",
        "adresa",
        "pasos"
    })
    public static class PodaciOPodnosiocuPrijave {

        @XmlElement(name = "OsnovneInformacije")
        protected Deo1Type.PodaciOPodnosiocuPrijave.OsnovneInformacije osnovneInformacije;
        @XmlElement(name = "Adresa")
        protected Deo1Type.PodaciOPodnosiocuPrijave.Adresa adresa;
        @XmlElement(name = "Pasos")
        protected Deo1Type.PodaciOPodnosiocuPrijave.Pasos pasos;

        /**
         * Gets the value of the osnovneInformacije property.
         * 
         * @return
         *     possible object is
         *     {@link Deo1Type.PodaciOPodnosiocuPrijave.OsnovneInformacije }
         *     
         */
        public Deo1Type.PodaciOPodnosiocuPrijave.OsnovneInformacije getOsnovneInformacije() {
            return osnovneInformacije;
        }

        /**
         * Sets the value of the osnovneInformacije property.
         * 
         * @param value
         *     allowed object is
         *     {@link Deo1Type.PodaciOPodnosiocuPrijave.OsnovneInformacije }
         *     
         */
        public void setOsnovneInformacije(Deo1Type.PodaciOPodnosiocuPrijave.OsnovneInformacije value) {
            this.osnovneInformacije = value;
        }

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link Deo1Type.PodaciOPodnosiocuPrijave.Adresa }
         *     
         */
        public Deo1Type.PodaciOPodnosiocuPrijave.Adresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link Deo1Type.PodaciOPodnosiocuPrijave.Adresa }
         *     
         */
        public void setAdresa(Deo1Type.PodaciOPodnosiocuPrijave.Adresa value) {
            this.adresa = value;
        }

        /**
         * Gets the value of the pasos property.
         * 
         * @return
         *     possible object is
         *     {@link Deo1Type.PodaciOPodnosiocuPrijave.Pasos }
         *     
         */
        public Deo1Type.PodaciOPodnosiocuPrijave.Pasos getPasos() {
            return pasos;
        }

        /**
         * Sets the value of the pasos property.
         * 
         * @param value
         *     allowed object is
         *     {@link Deo1Type.PodaciOPodnosiocuPrijave.Pasos }
         *     
         */
        public void setPasos(Deo1Type.PodaciOPodnosiocuPrijave.Pasos value) {
            this.pasos = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AdresaStanovanja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Grad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="PostanskiBroj" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="Drzava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "adresaStanovanja",
            "grad",
            "postanskiBroj",
            "drzava"
        })
        public static class Adresa {

            @XmlElement(name = "AdresaStanovanja")
            protected String adresaStanovanja;
            @XmlElement(name = "Grad")
            protected String grad;
            @XmlElement(name = "PostanskiBroj")
            protected Integer postanskiBroj;
            @XmlElement(name = "Drzava")
            protected String drzava;

            /**
             * Gets the value of the adresaStanovanja property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdresaStanovanja() {
                return adresaStanovanja;
            }

            /**
             * Sets the value of the adresaStanovanja property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdresaStanovanja(String value) {
                this.adresaStanovanja = value;
            }

            /**
             * Gets the value of the grad property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGrad() {
                return grad;
            }

            /**
             * Sets the value of the grad property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGrad(String value) {
                this.grad = value;
            }

            /**
             * Gets the value of the postanskiBroj property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getPostanskiBroj() {
                return postanskiBroj;
            }

            /**
             * Sets the value of the postanskiBroj property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setPostanskiBroj(Integer value) {
                this.postanskiBroj = value;
            }

            /**
             * Gets the value of the drzava property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDrzava() {
                return drzava;
            }

            /**
             * Sets the value of the drzava property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDrzava(String value) {
                this.drzava = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ImePrezime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Drzavljanstvo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DatumRodjenja" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="MestoRodjenja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Zanimanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "imePrezime",
            "drzavljanstvo",
            "datumRodjenja",
            "mestoRodjenja",
            "zanimanje"
        })
        public static class OsnovneInformacije {

            @XmlElement(name = "ImePrezime")
            protected String imePrezime;
            @XmlElement(name = "Drzavljanstvo")
            protected String drzavljanstvo;
            @XmlElement(name = "DatumRodjenja")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar datumRodjenja;
            @XmlElement(name = "MestoRodjenja")
            protected String mestoRodjenja;
            @XmlElement(name = "Zanimanje")
            protected String zanimanje;

            /**
             * Gets the value of the imePrezime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImePrezime() {
                return imePrezime;
            }

            /**
             * Sets the value of the imePrezime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImePrezime(String value) {
                this.imePrezime = value;
            }

            /**
             * Gets the value of the drzavljanstvo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDrzavljanstvo() {
                return drzavljanstvo;
            }

            /**
             * Sets the value of the drzavljanstvo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDrzavljanstvo(String value) {
                this.drzavljanstvo = value;
            }

            /**
             * Gets the value of the datumRodjenja property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDatumRodjenja() {
                return datumRodjenja;
            }

            /**
             * Sets the value of the datumRodjenja property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDatumRodjenja(XMLGregorianCalendar value) {
                this.datumRodjenja = value;
            }

            /**
             * Gets the value of the mestoRodjenja property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMestoRodjenja() {
                return mestoRodjenja;
            }

            /**
             * Sets the value of the mestoRodjenja property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMestoRodjenja(String value) {
                this.mestoRodjenja = value;
            }

            /**
             * Gets the value of the zanimanje property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZanimanje() {
                return zanimanje;
            }

            /**
             * Sets the value of the zanimanje property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZanimanje(String value) {
                this.zanimanje = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Broj" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="DatumIzdavanja" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="MestoIzdavanja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "broj",
            "datumIzdavanja",
            "mestoIzdavanja"
        })
        public static class Pasos {

            @XmlElement(name = "Broj")
            protected Integer broj;
            @XmlElement(name = "DatumIzdavanja")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar datumIzdavanja;
            @XmlElement(name = "MestoIzdavanja")
            protected String mestoIzdavanja;

            /**
             * Gets the value of the broj property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBroj() {
                return broj;
            }

            /**
             * Sets the value of the broj property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBroj(Integer value) {
                this.broj = value;
            }

            /**
             * Gets the value of the datumIzdavanja property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDatumIzdavanja() {
                return datumIzdavanja;
            }

            /**
             * Sets the value of the datumIzdavanja property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDatumIzdavanja(XMLGregorianCalendar value) {
                this.datumIzdavanja = value;
            }

            /**
             * Gets the value of the mestoIzdavanja property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMestoIzdavanja() {
                return mestoIzdavanja;
            }

            /**
             * Sets the value of the mestoIzdavanja property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMestoIzdavanja(String value) {
                this.mestoIzdavanja = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OsnovneInformacije" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ImePrezime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Drzavljanstvo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DatumRodjenja" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="MestoRodjenja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Zanimanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Adresa" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AdresaStanovanja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Grad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="PostanskiBroj" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="Drzava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Pasos" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Broj" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="DatumIzdavanja" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="MestoIzdavanja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "osnovneInformacije",
        "adresa",
        "pasos"
    })
    public static class PodaciOVlasnikuSredstava {

        @XmlElement(name = "OsnovneInformacije")
        protected Deo1Type.PodaciOVlasnikuSredstava.OsnovneInformacije osnovneInformacije;
        @XmlElement(name = "Adresa")
        protected Deo1Type.PodaciOVlasnikuSredstava.Adresa adresa;
        @XmlElement(name = "Pasos")
        protected Deo1Type.PodaciOVlasnikuSredstava.Pasos pasos;

        /**
         * Gets the value of the osnovneInformacije property.
         * 
         * @return
         *     possible object is
         *     {@link Deo1Type.PodaciOVlasnikuSredstava.OsnovneInformacije }
         *     
         */
        public Deo1Type.PodaciOVlasnikuSredstava.OsnovneInformacije getOsnovneInformacije() {
            return osnovneInformacije;
        }

        /**
         * Sets the value of the osnovneInformacije property.
         * 
         * @param value
         *     allowed object is
         *     {@link Deo1Type.PodaciOVlasnikuSredstava.OsnovneInformacije }
         *     
         */
        public void setOsnovneInformacije(Deo1Type.PodaciOVlasnikuSredstava.OsnovneInformacije value) {
            this.osnovneInformacije = value;
        }

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link Deo1Type.PodaciOVlasnikuSredstava.Adresa }
         *     
         */
        public Deo1Type.PodaciOVlasnikuSredstava.Adresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link Deo1Type.PodaciOVlasnikuSredstava.Adresa }
         *     
         */
        public void setAdresa(Deo1Type.PodaciOVlasnikuSredstava.Adresa value) {
            this.adresa = value;
        }

        /**
         * Gets the value of the pasos property.
         * 
         * @return
         *     possible object is
         *     {@link Deo1Type.PodaciOVlasnikuSredstava.Pasos }
         *     
         */
        public Deo1Type.PodaciOVlasnikuSredstava.Pasos getPasos() {
            return pasos;
        }

        /**
         * Sets the value of the pasos property.
         * 
         * @param value
         *     allowed object is
         *     {@link Deo1Type.PodaciOVlasnikuSredstava.Pasos }
         *     
         */
        public void setPasos(Deo1Type.PodaciOVlasnikuSredstava.Pasos value) {
            this.pasos = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AdresaStanovanja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Grad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="PostanskiBroj" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="Drzava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "adresaStanovanja",
            "grad",
            "postanskiBroj",
            "drzava"
        })
        public static class Adresa {

            @XmlElement(name = "AdresaStanovanja")
            protected String adresaStanovanja;
            @XmlElement(name = "Grad")
            protected String grad;
            @XmlElement(name = "PostanskiBroj")
            protected Integer postanskiBroj;
            @XmlElement(name = "Drzava")
            protected String drzava;

            /**
             * Gets the value of the adresaStanovanja property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdresaStanovanja() {
                return adresaStanovanja;
            }

            /**
             * Sets the value of the adresaStanovanja property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdresaStanovanja(String value) {
                this.adresaStanovanja = value;
            }

            /**
             * Gets the value of the grad property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGrad() {
                return grad;
            }

            /**
             * Sets the value of the grad property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGrad(String value) {
                this.grad = value;
            }

            /**
             * Gets the value of the postanskiBroj property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getPostanskiBroj() {
                return postanskiBroj;
            }

            /**
             * Sets the value of the postanskiBroj property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setPostanskiBroj(Integer value) {
                this.postanskiBroj = value;
            }

            /**
             * Gets the value of the drzava property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDrzava() {
                return drzava;
            }

            /**
             * Sets the value of the drzava property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDrzava(String value) {
                this.drzava = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ImePrezime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Drzavljanstvo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DatumRodjenja" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="MestoRodjenja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Zanimanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "imePrezime",
            "drzavljanstvo",
            "datumRodjenja",
            "mestoRodjenja",
            "zanimanje"
        })
        public static class OsnovneInformacije {

            @XmlElement(name = "ImePrezime")
            protected String imePrezime;
            @XmlElement(name = "Drzavljanstvo")
            protected String drzavljanstvo;
            @XmlElement(name = "DatumRodjenja")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar datumRodjenja;
            @XmlElement(name = "MestoRodjenja")
            protected String mestoRodjenja;
            @XmlElement(name = "Zanimanje")
            protected String zanimanje;

            /**
             * Gets the value of the imePrezime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImePrezime() {
                return imePrezime;
            }

            /**
             * Sets the value of the imePrezime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImePrezime(String value) {
                this.imePrezime = value;
            }

            /**
             * Gets the value of the drzavljanstvo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDrzavljanstvo() {
                return drzavljanstvo;
            }

            /**
             * Sets the value of the drzavljanstvo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDrzavljanstvo(String value) {
                this.drzavljanstvo = value;
            }

            /**
             * Gets the value of the datumRodjenja property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDatumRodjenja() {
                return datumRodjenja;
            }

            /**
             * Sets the value of the datumRodjenja property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDatumRodjenja(XMLGregorianCalendar value) {
                this.datumRodjenja = value;
            }

            /**
             * Gets the value of the mestoRodjenja property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMestoRodjenja() {
                return mestoRodjenja;
            }

            /**
             * Sets the value of the mestoRodjenja property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMestoRodjenja(String value) {
                this.mestoRodjenja = value;
            }

            /**
             * Gets the value of the zanimanje property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZanimanje() {
                return zanimanje;
            }

            /**
             * Sets the value of the zanimanje property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZanimanje(String value) {
                this.zanimanje = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Broj" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="DatumIzdavanja" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="MestoIzdavanja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "broj",
            "datumIzdavanja",
            "mestoIzdavanja"
        })
        public static class Pasos {

            @XmlElement(name = "Broj")
            protected Integer broj;
            @XmlElement(name = "DatumIzdavanja")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar datumIzdavanja;
            @XmlElement(name = "MestoIzdavanja")
            protected String mestoIzdavanja;

            /**
             * Gets the value of the broj property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBroj() {
                return broj;
            }

            /**
             * Sets the value of the broj property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBroj(Integer value) {
                this.broj = value;
            }

            /**
             * Gets the value of the datumIzdavanja property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDatumIzdavanja() {
                return datumIzdavanja;
            }

            /**
             * Sets the value of the datumIzdavanja property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDatumIzdavanja(XMLGregorianCalendar value) {
                this.datumIzdavanja = value;
            }

            /**
             * Gets the value of the mestoIzdavanja property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMestoIzdavanja() {
                return mestoIzdavanja;
            }

            /**
             * Sets the value of the mestoIzdavanja property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMestoIzdavanja(String value) {
                this.mestoIzdavanja = value;
            }

        }

    }

}
