//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 09:15:18 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Deo2OpisFizickiPrenosivihSredstavaPlacanjaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Deo2OpisFizickiPrenosivihSredstavaPlacanjaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Novcanice" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Iznos" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="Valuta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Cekovi" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Iznos" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="Valuta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Drugo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Iznos" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="Valuta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Deo2OpisFizickiPrenosivihSredstavaPlacanjaType", propOrder = {
    "novcanice",
    "cekovi",
    "drugo"
})
public class Deo2OpisFizickiPrenosivihSredstavaPlacanjaType {

    @XmlElement(name = "Novcanice")
    protected Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Novcanice novcanice;
    @XmlElement(name = "Cekovi")
    protected Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Cekovi cekovi;
    @XmlElement(name = "Drugo")
    protected Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Drugo drugo;

    /**
     * Gets the value of the novcanice property.
     * 
     * @return
     *     possible object is
     *     {@link Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Novcanice }
     *     
     */
    public Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Novcanice getNovcanice() {
        return novcanice;
    }

    /**
     * Sets the value of the novcanice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Novcanice }
     *     
     */
    public void setNovcanice(Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Novcanice value) {
        this.novcanice = value;
    }

    /**
     * Gets the value of the cekovi property.
     * 
     * @return
     *     possible object is
     *     {@link Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Cekovi }
     *     
     */
    public Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Cekovi getCekovi() {
        return cekovi;
    }

    /**
     * Sets the value of the cekovi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Cekovi }
     *     
     */
    public void setCekovi(Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Cekovi value) {
        this.cekovi = value;
    }

    /**
     * Gets the value of the drugo property.
     * 
     * @return
     *     possible object is
     *     {@link Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Drugo }
     *     
     */
    public Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Drugo getDrugo() {
        return drugo;
    }

    /**
     * Sets the value of the drugo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Drugo }
     *     
     */
    public void setDrugo(Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Drugo value) {
        this.drugo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Iznos" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="Valuta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "iznos",
        "valuta"
    })
    public static class Cekovi {

        @XmlElement(name = "Iznos")
        protected Float iznos;
        @XmlElement(name = "Valuta")
        protected String valuta;

        /**
         * Gets the value of the iznos property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getIznos() {
            return iznos;
        }

        /**
         * Sets the value of the iznos property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setIznos(Float value) {
            this.iznos = value;
        }

        /**
         * Gets the value of the valuta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValuta() {
            return valuta;
        }

        /**
         * Sets the value of the valuta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValuta(String value) {
            this.valuta = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Iznos" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="Valuta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "iznos",
        "valuta"
    })
    public static class Drugo {

        @XmlElement(name = "Iznos")
        protected Float iznos;
        @XmlElement(name = "Valuta")
        protected String valuta;

        /**
         * Gets the value of the iznos property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getIznos() {
            return iznos;
        }

        /**
         * Sets the value of the iznos property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setIznos(Float value) {
            this.iznos = value;
        }

        /**
         * Gets the value of the valuta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValuta() {
            return valuta;
        }

        /**
         * Sets the value of the valuta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValuta(String value) {
            this.valuta = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Iznos" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="Valuta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "iznos",
        "valuta"
    })
    public static class Novcanice {

        @XmlElement(name = "Iznos")
        protected Float iznos;
        @XmlElement(name = "Valuta")
        protected String valuta;

        /**
         * Gets the value of the iznos property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getIznos() {
            return iznos;
        }

        /**
         * Sets the value of the iznos property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setIznos(Float value) {
            this.iznos = value;
        }

        /**
         * Gets the value of the valuta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValuta() {
            return valuta;
        }

        /**
         * Sets the value of the valuta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValuta(String value) {
            this.valuta = value;
        }

    }

}
