//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 09:15:18 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Poreklo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrimalacSredstava" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ImePrezime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Adresa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NamenaSredstava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType", propOrder = {
    "poreklo",
    "primalacSredstava",
    "namenaSredstava"
})
public class Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType {

    @XmlElement(name = "Poreklo")
    protected String poreklo;
    @XmlElement(name = "PrimalacSredstava")
    protected Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType.PrimalacSredstava primalacSredstava;
    @XmlElement(name = "NamenaSredstava")
    protected String namenaSredstava;

    /**
     * Gets the value of the poreklo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoreklo() {
        return poreklo;
    }

    /**
     * Sets the value of the poreklo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoreklo(String value) {
        this.poreklo = value;
    }

    /**
     * Gets the value of the primalacSredstava property.
     * 
     * @return
     *     possible object is
     *     {@link Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType.PrimalacSredstava }
     *     
     */
    public Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType.PrimalacSredstava getPrimalacSredstava() {
        return primalacSredstava;
    }

    /**
     * Sets the value of the primalacSredstava property.
     * 
     * @param value
     *     allowed object is
     *     {@link Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType.PrimalacSredstava }
     *     
     */
    public void setPrimalacSredstava(Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType.PrimalacSredstava value) {
        this.primalacSredstava = value;
    }

    /**
     * Gets the value of the namenaSredstava property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamenaSredstava() {
        return namenaSredstava;
    }

    /**
     * Sets the value of the namenaSredstava property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamenaSredstava(String value) {
        this.namenaSredstava = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ImePrezime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Adresa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imePrezime",
        "adresa"
    })
    public static class PrimalacSredstava {

        @XmlElement(name = "ImePrezime")
        protected String imePrezime;
        @XmlElement(name = "Adresa")
        protected String adresa;

        /**
         * Gets the value of the imePrezime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImePrezime() {
            return imePrezime;
        }

        /**
         * Sets the value of the imePrezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImePrezime(String value) {
            this.imePrezime = value;
        }

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdresa(String value) {
            this.adresa = value;
        }

    }

}
