//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 09:15:18 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Deo4PodaciOPrevozuType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Deo4PodaciOPrevozuType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NacinPrevoza" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Vazdusni"/>
 *               &lt;enumeration value="Drumski"/>
 *               &lt;enumeration value="Zeleznicki"/>
 *               &lt;enumeration value="Recni"/>
 *               &lt;enumeration value="Drugi"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NacinPrevozaDrugi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Marsuta" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ZemljaPolaska" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ZemljaTranzita" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ZemljaDolaska" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DatumPolaska" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="DatumDolaska" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="TransportnoPreduzece" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ReferentniBroj" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="DaLiJeOvoVasPrviDolazak" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Da"/>
 *                         &lt;enumeration value="Ne"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="BrojDolazaka" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Deo4PodaciOPrevozuType", propOrder = {
    "nacinPrevoza",
    "nacinPrevozaDrugi",
    "marsuta"
})
public class Deo4PodaciOPrevozuType {

    @XmlElement(name = "NacinPrevoza")
    protected String nacinPrevoza;
    @XmlElement(name = "NacinPrevozaDrugi")
    protected String nacinPrevozaDrugi;
    @XmlElement(name = "Marsuta")
    protected Deo4PodaciOPrevozuType.Marsuta marsuta;

    /**
     * Gets the value of the nacinPrevoza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNacinPrevoza() {
        return nacinPrevoza;
    }

    /**
     * Sets the value of the nacinPrevoza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNacinPrevoza(String value) {
        this.nacinPrevoza = value;
    }

    /**
     * Gets the value of the nacinPrevozaDrugi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNacinPrevozaDrugi() {
        return nacinPrevozaDrugi;
    }

    /**
     * Sets the value of the nacinPrevozaDrugi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNacinPrevozaDrugi(String value) {
        this.nacinPrevozaDrugi = value;
    }

    /**
     * Gets the value of the marsuta property.
     * 
     * @return
     *     possible object is
     *     {@link Deo4PodaciOPrevozuType.Marsuta }
     *     
     */
    public Deo4PodaciOPrevozuType.Marsuta getMarsuta() {
        return marsuta;
    }

    /**
     * Sets the value of the marsuta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Deo4PodaciOPrevozuType.Marsuta }
     *     
     */
    public void setMarsuta(Deo4PodaciOPrevozuType.Marsuta value) {
        this.marsuta = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ZemljaPolaska" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ZemljaTranzita" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ZemljaDolaska" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DatumPolaska" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="DatumDolaska" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="TransportnoPreduzece" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ReferentniBroj" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="DaLiJeOvoVasPrviDolazak" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Da"/>
     *               &lt;enumeration value="Ne"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="BrojDolazaka" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zemljaPolaska",
        "zemljaTranzita",
        "zemljaDolaska",
        "datumPolaska",
        "datumDolaska",
        "transportnoPreduzece",
        "referentniBroj",
        "daLiJeOvoVasPrviDolazak",
        "brojDolazaka"
    })
    public static class Marsuta {

        @XmlElement(name = "ZemljaPolaska")
        protected String zemljaPolaska;
        @XmlElement(name = "ZemljaTranzita")
        protected String zemljaTranzita;
        @XmlElement(name = "ZemljaDolaska")
        protected String zemljaDolaska;
        @XmlElement(name = "DatumPolaska")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPolaska;
        @XmlElement(name = "DatumDolaska")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumDolaska;
        @XmlElement(name = "TransportnoPreduzece")
        protected String transportnoPreduzece;
        @XmlElement(name = "ReferentniBroj")
        protected Integer referentniBroj;
        @XmlElement(name = "DaLiJeOvoVasPrviDolazak")
        protected String daLiJeOvoVasPrviDolazak;
        @XmlElement(name = "BrojDolazaka")
        protected Integer brojDolazaka;

        /**
         * Gets the value of the zemljaPolaska property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZemljaPolaska() {
            return zemljaPolaska;
        }

        /**
         * Sets the value of the zemljaPolaska property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZemljaPolaska(String value) {
            this.zemljaPolaska = value;
        }

        /**
         * Gets the value of the zemljaTranzita property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZemljaTranzita() {
            return zemljaTranzita;
        }

        /**
         * Sets the value of the zemljaTranzita property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZemljaTranzita(String value) {
            this.zemljaTranzita = value;
        }

        /**
         * Gets the value of the zemljaDolaska property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZemljaDolaska() {
            return zemljaDolaska;
        }

        /**
         * Sets the value of the zemljaDolaska property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZemljaDolaska(String value) {
            this.zemljaDolaska = value;
        }

        /**
         * Gets the value of the datumPolaska property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPolaska() {
            return datumPolaska;
        }

        /**
         * Sets the value of the datumPolaska property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPolaska(XMLGregorianCalendar value) {
            this.datumPolaska = value;
        }

        /**
         * Gets the value of the datumDolaska property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumDolaska() {
            return datumDolaska;
        }

        /**
         * Sets the value of the datumDolaska property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumDolaska(XMLGregorianCalendar value) {
            this.datumDolaska = value;
        }

        /**
         * Gets the value of the transportnoPreduzece property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransportnoPreduzece() {
            return transportnoPreduzece;
        }

        /**
         * Sets the value of the transportnoPreduzece property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransportnoPreduzece(String value) {
            this.transportnoPreduzece = value;
        }

        /**
         * Gets the value of the referentniBroj property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getReferentniBroj() {
            return referentniBroj;
        }

        /**
         * Sets the value of the referentniBroj property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setReferentniBroj(Integer value) {
            this.referentniBroj = value;
        }

        /**
         * Gets the value of the daLiJeOvoVasPrviDolazak property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDaLiJeOvoVasPrviDolazak() {
            return daLiJeOvoVasPrviDolazak;
        }

        /**
         * Sets the value of the daLiJeOvoVasPrviDolazak property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDaLiJeOvoVasPrviDolazak(String value) {
            this.daLiJeOvoVasPrviDolazak = value;
        }

        /**
         * Gets the value of the brojDolazaka property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getBrojDolazaka() {
            return brojDolazaka;
        }

        /**
         * Sets the value of the brojDolazaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBrojDolazaka(Integer value) {
            this.brojDolazaka = value;
        }

    }

}
