//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 09:15:18 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Deo4PodaciOPrevozuType }
     * 
     */
    public Deo4PodaciOPrevozuType createDeo4PodaciOPrevozuType() {
        return new Deo4PodaciOPrevozuType();
    }

    /**
     * Create an instance of {@link Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType }
     * 
     */
    public Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType createDeo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType() {
        return new Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType();
    }

    /**
     * Create an instance of {@link Deo2OpisFizickiPrenosivihSredstavaPlacanjaType }
     * 
     */
    public Deo2OpisFizickiPrenosivihSredstavaPlacanjaType createDeo2OpisFizickiPrenosivihSredstavaPlacanjaType() {
        return new Deo2OpisFizickiPrenosivihSredstavaPlacanjaType();
    }

    /**
     * Create an instance of {@link Deo1Type }
     * 
     */
    public Deo1Type createDeo1Type() {
        return new Deo1Type();
    }

    /**
     * Create an instance of {@link Deo1Type.PodaciOVlasnikuSredstava }
     * 
     */
    public Deo1Type.PodaciOVlasnikuSredstava createDeo1TypePodaciOVlasnikuSredstava() {
        return new Deo1Type.PodaciOVlasnikuSredstava();
    }

    /**
     * Create an instance of {@link Deo1Type.PodaciOPodnosiocuPrijave }
     * 
     */
    public Deo1Type.PodaciOPodnosiocuPrijave createDeo1TypePodaciOPodnosiocuPrijave() {
        return new Deo1Type.PodaciOPodnosiocuPrijave();
    }

    /**
     * Create an instance of {@link ObrazacPPS1 }
     * 
     */
    public ObrazacPPS1 createObrazacPPS1() {
        return new ObrazacPPS1();
    }

    /**
     * Create an instance of {@link ObrazacPPS1Type }
     * 
     */
    public ObrazacPPS1Type createObrazacPPS1Type() {
        return new ObrazacPPS1Type();
    }

    /**
     * Create an instance of {@link OsnovneInformacijeType }
     * 
     */
    public OsnovneInformacijeType createOsnovneInformacijeType() {
        return new OsnovneInformacijeType();
    }

    /**
     * Create an instance of {@link ZakljucakType }
     * 
     */
    public ZakljucakType createZakljucakType() {
        return new ZakljucakType();
    }

    /**
     * Create an instance of {@link Deo4PodaciOPrevozuType.Marsuta }
     * 
     */
    public Deo4PodaciOPrevozuType.Marsuta createDeo4PodaciOPrevozuTypeMarsuta() {
        return new Deo4PodaciOPrevozuType.Marsuta();
    }

    /**
     * Create an instance of {@link Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType.PrimalacSredstava }
     * 
     */
    public Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType.PrimalacSredstava createDeo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaTypePrimalacSredstava() {
        return new Deo3PorekloINamenaFizickiPrenosivihSredstavaPlacanjaType.PrimalacSredstava();
    }

    /**
     * Create an instance of {@link Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Novcanice }
     * 
     */
    public Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Novcanice createDeo2OpisFizickiPrenosivihSredstavaPlacanjaTypeNovcanice() {
        return new Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Novcanice();
    }

    /**
     * Create an instance of {@link Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Cekovi }
     * 
     */
    public Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Cekovi createDeo2OpisFizickiPrenosivihSredstavaPlacanjaTypeCekovi() {
        return new Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Cekovi();
    }

    /**
     * Create an instance of {@link Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Drugo }
     * 
     */
    public Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Drugo createDeo2OpisFizickiPrenosivihSredstavaPlacanjaTypeDrugo() {
        return new Deo2OpisFizickiPrenosivihSredstavaPlacanjaType.Drugo();
    }

    /**
     * Create an instance of {@link Deo1Type.PodaciOVlasnikuSredstava.OsnovneInformacije }
     * 
     */
    public Deo1Type.PodaciOVlasnikuSredstava.OsnovneInformacije createDeo1TypePodaciOVlasnikuSredstavaOsnovneInformacije() {
        return new Deo1Type.PodaciOVlasnikuSredstava.OsnovneInformacije();
    }

    /**
     * Create an instance of {@link Deo1Type.PodaciOVlasnikuSredstava.Adresa }
     * 
     */
    public Deo1Type.PodaciOVlasnikuSredstava.Adresa createDeo1TypePodaciOVlasnikuSredstavaAdresa() {
        return new Deo1Type.PodaciOVlasnikuSredstava.Adresa();
    }

    /**
     * Create an instance of {@link Deo1Type.PodaciOVlasnikuSredstava.Pasos }
     * 
     */
    public Deo1Type.PodaciOVlasnikuSredstava.Pasos createDeo1TypePodaciOVlasnikuSredstavaPasos() {
        return new Deo1Type.PodaciOVlasnikuSredstava.Pasos();
    }

    /**
     * Create an instance of {@link Deo1Type.PodaciOPodnosiocuPrijave.OsnovneInformacije }
     * 
     */
    public Deo1Type.PodaciOPodnosiocuPrijave.OsnovneInformacije createDeo1TypePodaciOPodnosiocuPrijaveOsnovneInformacije() {
        return new Deo1Type.PodaciOPodnosiocuPrijave.OsnovneInformacije();
    }

    /**
     * Create an instance of {@link Deo1Type.PodaciOPodnosiocuPrijave.Adresa }
     * 
     */
    public Deo1Type.PodaciOPodnosiocuPrijave.Adresa createDeo1TypePodaciOPodnosiocuPrijaveAdresa() {
        return new Deo1Type.PodaciOPodnosiocuPrijave.Adresa();
    }

    /**
     * Create an instance of {@link Deo1Type.PodaciOPodnosiocuPrijave.Pasos }
     * 
     */
    public Deo1Type.PodaciOPodnosiocuPrijave.Pasos createDeo1TypePodaciOPodnosiocuPrijavePasos() {
        return new Deo1Type.PodaciOPodnosiocuPrijave.Pasos();
    }

}
