//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 09:15:18 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OsnovneInformacijeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OsnovneInformacijeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatumPrijemaPrijave" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="PrijavaPrenosa">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Da"/>
 *               &lt;enumeration value="Ne"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NadlezniOrgan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GranicniPrelaz" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VrstaPrijave">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Ulazak u RS"/>
 *               &lt;enumeration value="Izlazak iz RS"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OsnovneInformacijeType", propOrder = {
    "datumPrijemaPrijave",
    "prijavaPrenosa",
    "nadlezniOrgan",
    "granicniPrelaz",
    "vrstaPrijave"
})
public class OsnovneInformacijeType {

    @XmlElement(name = "DatumPrijemaPrijave", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPrijemaPrijave;
    @XmlElement(name = "PrijavaPrenosa", required = true)
    protected String prijavaPrenosa;
    @XmlElement(name = "NadlezniOrgan", required = true)
    protected String nadlezniOrgan;
    @XmlElement(name = "GranicniPrelaz", required = true)
    protected String granicniPrelaz;
    @XmlElement(name = "VrstaPrijave", required = true)
    protected String vrstaPrijave;

    /**
     * Gets the value of the datumPrijemaPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPrijemaPrijave() {
        return datumPrijemaPrijave;
    }

    /**
     * Sets the value of the datumPrijemaPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPrijemaPrijave(XMLGregorianCalendar value) {
        this.datumPrijemaPrijave = value;
    }

    /**
     * Gets the value of the prijavaPrenosa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrijavaPrenosa() {
        return prijavaPrenosa;
    }

    /**
     * Sets the value of the prijavaPrenosa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrijavaPrenosa(String value) {
        this.prijavaPrenosa = value;
    }

    /**
     * Gets the value of the nadlezniOrgan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNadlezniOrgan() {
        return nadlezniOrgan;
    }

    /**
     * Sets the value of the nadlezniOrgan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNadlezniOrgan(String value) {
        this.nadlezniOrgan = value;
    }

    /**
     * Gets the value of the granicniPrelaz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGranicniPrelaz() {
        return granicniPrelaz;
    }

    /**
     * Sets the value of the granicniPrelaz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGranicniPrelaz(String value) {
        this.granicniPrelaz = value;
    }

    /**
     * Gets the value of the vrstaPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrstaPrijave() {
        return vrstaPrijave;
    }

    /**
     * Sets the value of the vrstaPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrstaPrijave(String value) {
        this.vrstaPrijave = value;
    }

}
