//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 09:15:18 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZakljucakType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZakljucakType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PotpisPodnosioca" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrimedbeNadleznogOrgana" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZakljucakType", propOrder = {
    "potpisPodnosioca",
    "primedbeNadleznogOrgana"
})
public class ZakljucakType {

    @XmlElement(name = "PotpisPodnosioca")
    protected String potpisPodnosioca;
    @XmlElement(name = "PrimedbeNadleznogOrgana")
    protected String primedbeNadleznogOrgana;

    /**
     * Gets the value of the potpisPodnosioca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotpisPodnosioca() {
        return potpisPodnosioca;
    }

    /**
     * Sets the value of the potpisPodnosioca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotpisPodnosioca(String value) {
        this.potpisPodnosioca = value;
    }

    /**
     * Gets the value of the primedbeNadleznogOrgana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimedbeNadleznogOrgana() {
        return primedbeNadleznogOrgana;
    }

    /**
     * Sets the value of the primedbeNadleznogOrgana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimedbeNadleznogOrgana(String value) {
        this.primedbeNadleznogOrgana = value;
    }

}
